spring:
  application:
    name: project
  datasource:
    url: jdbc:mysql://localhost:3306/rdep_project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  messages:
    basename: messages/message
    encoding: utf-8
  jpa:
    show-sql: true

server:
  port: 0

logging:
  level:
    root: info
    org.hibernate: INFO

dubbo:
  application:
    name: project
  registry:
    address: zookeeper://127.0.0.1:2181?client=curator
  protocol:
    serialization: fst
  scan:
    basePackages: xyz.luomu32.rdep.project.service.dubbo