spring:
  application:
    name: project
  datasource:
    url: jdbc:mysql://${mysql.host:localhost}:3306/rdep_project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  messages:
    basename: messages/message,common-messages/message
    encoding: utf-8
  jpa:
    show-sql: true
    openInView: false
  cloud:
    zookeeper:
      connectString: ${zk.host:localhost}:2181
  servlet:
    multipart:
      max-file-size: 20MB #单个文件最大
      max-request-size: 200MB #总上传数据总大小

server:
  port: 0

#feign:
#  client:
#    config:
#      jenkins:
#        requestInterceptors:
#          - feign.auth.BasicAuthRequestInterceptor

jenkins:
  host: localhost:8989

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    org.hibernate: INFO

dubbo:
  application:
    name: project
  registry:
    address: zookeeper://127.0.0.1:2181?client=curator
  protocol:
    serialization: fst
  scan:
    basePackages: xyz.luomu32.rdep.project.service.dubbo
