spring:
  application:
    name: project
  datasource:
    url: jdbc:mysql://${mysql.host:localhost}:3306/rdep_project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  messages:
    basename: messages/message,common-messages/message
    encoding: utf-8
  jpa:
    show-sql: true
    openInView: false
    properties:
      hibernate.dialect.storage_engine: innodb

  cloud:
    zookeeper:
      connectString: ${zk.host:localhost}:2181

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    org.hibernate: INFO

dubbo:
  application:
    name: project
  registry:
    address: zookeeper://127.0.0.1:2181?client=curator
  protocol:
    serialization: fst
  scan:
    basePackages: xyz.luomu32.rdep.project.service.dubbo

---
spring:
  profiles: dev
  datasource:
    url: jdbc:p6spy:mysql://${mysql.host:localhost}:3306/rdep_project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
logging:
  level:
#    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
