spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/rdep_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  messages:
    basename: messages/message,common-messages/message
    encoding: utf-8
    useCodeAsDefaultMessage: true

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    org.hibernate: INFO
