spring:
  application:
    name: middleware
  datasource:
    url: jdbc:mysql://${mysql.host:localhost}:3306/rdep_middleware?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connectString: ${zk.host:localhost}:2181

server:
  port: 0
logging:
  root:
    level: debug