spring:
  datasource:
    url: jdbc://localhost:3306/rdep_project?useSSL=false
    username: root
    password: 123456

  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    org.hibernate: INFO